wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690968661.692764
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.15.0
      8:
      - 5
